package eifml.generator.context


import contextML.impl.EntityImpl
import contextML.impl.PropertyImpl
import eifml.generator.general.AbstractFileGenerator

class ContextEntityGenerator extends AbstractFileGenerator<EntityImpl> {
	
	override protected fileContents(EntityImpl entity) {
		'''
			// Generated by ContextEntityGenerator
			
			// contains properties for «entity.eClass.name» context
			
			export class «entity.eClass.name»Profile {
				
				«FOR reference: entity.eContents»
					private «reference.eClass.name.toFirstLower»:«(reference as PropertyImpl).type»
				«ENDFOR»
			
			    
			    constructor(){};
			    
			    «FOR reference: entity.eContents»
			    	public set«reference.eClass.name.toFirstUpper»(v:«(reference as PropertyImpl).type»){
			    		this.«reference.eClass.name.toFirstLower» = v;
			    	}; 
			    	
			    	
			   «ENDFOR»
			   
			   «FOR reference: entity.eContents»
			   public get«reference.eClass.name.toFirstUpper»():«(reference as PropertyImpl).type»{
			   return this.«reference.eClass.name.toFirstLower»;
			   }; 
			  	«ENDFOR»
			
			}
			
		'''
	}
	
	override protected fileName(EntityImpl entity) {
		var entityName = entity.eClass.name;
		
		'''«entityName.toFirstLower».profile.ts'''
	}
	
	override protected folderName(EntityImpl entity) {
		'''app/context/profile/'''
	}
}
